/** True when running inside the Tauri shell (vs. plain `vite dev` in a browser tab). */
export function isTauriRuntime(): boolean {
  return typeof window !== "undefined" && "__TAURI_INTERNALS__" in window;
}

/** Normalize separators and strip trailing slashes for prefix checks. */
export function normalizeFsPath(path: string): string {
  return path.replace(/\\/g, "/").replace(/\/+$/, "");
}

/** True when `filePath` is the workspace root or a path under it. */
export function isPathUnderWorkspace(filePath: string, workspacePath: string): boolean {
  const file = normalizeFsPath(filePath);
  const root = normalizeFsPath(workspacePath);
  if (!file || !root) return false;
  const fileKey = file.toLowerCase();
  const rootKey = root.toLowerCase();
  return fileKey === rootKey || fileKey.startsWith(`${rootKey}/`);
}

export function filterPathsUnderWorkspace(
  paths: string[],
  workspacePath: string,
): { accepted: string[]; rejected: string[] } {
  const accepted: string[] = [];
  const rejected: string[] = [];
  for (const raw of paths) {
    const path = raw.trim();
    if (!path) continue;
    if (isPathUnderWorkspace(path, workspacePath)) accepted.push(normalizeFsPath(path));
    else rejected.push(path);
  }
  return { accepted, rejected };
}

/** Parse absolute paths pasted one-per-line (browser fallback). */
export function parsePastedPaths(text: string): string[] {
  return text
    .split(/\r?\n/)
    .map((line) => line.trim())
    .filter(Boolean);
}

/**
 * Opens the native "choose folder" dialog via the Rust `pick_folder`
 * command. Returns `null` when unavailable (browser dev mode) or cancelled.
 */
export async function pickFolder(): Promise<string | null> {
  if (!isTauriRuntime()) return null;
  const { invoke } = await import("@tauri-apps/api/core");
  const result = await invoke<string | null>("pick_folder");
  return result ?? null;
}

/** Pick a Skill zip or markdown file. Browser mode returns null. */
export async function pickSkillFile(): Promise<string | null> {
  if (!isTauriRuntime()) return null;
  const { invoke } = await import("@tauri-apps/api/core");
  const result = await invoke<string | null>("pick_skill_file");
  return result ?? null;
}

/** Runtime Bearer token generated by the Tauri shell (null in browser dev). */
export async function getRuntimeToken(): Promise<string | null> {
  if (!isTauriRuntime()) return null;
  const { invoke } = await import("@tauri-apps/api/core");
  return invoke<string>("get_runtime_token");
}

/**
 * Multi-select files via `@tauri-apps/plugin-dialog`.
 * Returns `null` when cancelled or unavailable (browser / non-Tauri).
 */
export async function pickFiles(options?: {
  defaultPath?: string;
  title?: string;
}): Promise<string[] | null> {
  if (!isTauriRuntime()) return null;
  const { open } = await import("@tauri-apps/plugin-dialog");
  const selected = await open({
    multiple: true,
    directory: false,
    defaultPath: options?.defaultPath,
    title: options?.title ?? "选择附件",
  });
  if (selected === null) return null;
  return Array.isArray(selected) ? selected : [selected];
}

/**
 * Open a local path with the OS default app via `@tauri-apps/plugin-opener`.
 * Throws when not in Tauri or when the native open fails.
 */
export async function openPath(path: string): Promise<void> {
  if (!isTauriRuntime()) {
    throw new Error("当前为浏览器模式，无法用系统应用打开文件");
  }
  const { openPath: openNativePath } = await import("@tauri-apps/plugin-opener");
  await openNativePath(path);
}

/** Known deliverable suffixes for path linkification. */
export const DELIVERABLE_SUFFIXES = [
  ".docx",
  ".xlsx",
  ".pptx",
  ".ppt",
  ".pdf",
  ".md",
  ".txt",
  ".json",
] as const;

/** Extension alternation for path scanners (no leading dots), e.g. `docx|xlsx|pptx`. */
export const DELIVERABLE_EXT_ALT = DELIVERABLE_SUFFIXES.map((s) => s.slice(1)).join("|");

const DELIVERABLE_SUFFIX_RE = new RegExp(`\\.(?:${DELIVERABLE_EXT_ALT})$`, "i");

/** True when path has a known deliverable extension. */
export function hasDeliverableSuffix(path: string): boolean {
  return DELIVERABLE_SUFFIX_RE.test(path.trim());
}

/**
 * Relative deliverable fragment in backticks, e.g. `output/a.docx` or `.office-agent/b.md`.
 * Rejects absolute paths and `..` segments.
 */
export function isRelativeDeliverablePath(path: string): boolean {
  const p = path.trim().replace(/\\/g, "/");
  if (!p || p.startsWith("/") || /^[a-zA-Z]:\//.test(p)) return false;
  if (p.includes("..")) return false;
  if (!hasDeliverableSuffix(p)) return false;
  return /^(output\/|\.office-agent\/)/.test(p) || !p.startsWith(".");
}

/** Join workspace root with a relative path (forward slashes). */
export function resolveUnderWorkspace(workspacePath: string, relativePath: string): string {
  const root = normalizeFsPath(workspacePath);
  const rel = relativePath.trim().replace(/\\/g, "/").replace(/^\.\//, "");
  return `${root}/${rel}`;
}
